# Part 1: the goal, to be sent by the client
#
# Degree the robots need to rotate and the velocity
float32 distance
float32 linear_velocity
---
# Part 2: the result, to be sent by the server upon completion
---
# Part 3: the feedback, to be sent periodically by the server during execution.